[cnn-base-model-1]
dir = "results/MNIST_CNN/checkpoints_base_model_1"
dataset = "mnist"
data-path = "datasets/"
model = "CNN"
epochs = 10
lr = 0.05
wd = 0.0005
seed = 1

[cnn-base-model-2]
dir = "results/MNIST_CNN/checkpoints_base_model_2"
dataset = "mnist"
data-path = "datasets/"
model = "CNN"
epochs = 10
lr = 0.05
wd = 0.0005
seed = 42

[cnn-curve-pretrained]
dir = "results/MNIST_CNN/checkpoints_curve"
dataset = "mnist"
data-path = "datasets/"
model = "CNN"
curve = "Bezier"
num-bends = 1
epochs = 10
lr = 0.05
wd = 0.0005
init-start = "results/MNIST_CNN/checkpoints_base_model_1/model-weights-epoch10"
fix-start = true
init-end = "results/MNIST_CNN/checkpoints_base_model_2/model-weights-epoch10"
fix-end = true

[cnn-curve-resume]
dir = "results/MNIST_CNN/checkpoints_curve"
dataset="mnist"
data-path="datasets/"
ckpt="results/MNIST_CNN/checkpoints_curve/model-weights-epoch10"
resume-epoch=11
model="CNN"
curve="Bezier"
num-bends=1
epochs=15
lr=0.001
wd=0.0005
fix-start = true
fix-end = true

[cnn-curve-evaluate-init]
dir = "results/MNIST_CNN/evaluation_curve"
dataset = "mnist"
data-path = "datasets/"
model = "CNN"
curve = "Bezier"
num-bends = 1
wd = 0.0005
ckpt = "results/MNIST_CNN/checkpoints_curve/model-weights-epoch0"
init-linear = false
fix-start = true
fix-end = true
num-points = 11
file-name-appendix = "_epoch0"

[cnn-curve-evaluate-trained]
dir = "results/MNIST_CNN/evaluation_curve"
dataset = "mnist"
data-path = "datasets/"
model = "CNN"
curve = "Bezier"
num-bends = 1
wd = 0.0005
ckpt = "results/MNIST_CNN/checkpoints_curve/model-weights-epoch15"
init-linear = false
fix-start = true
fix-end = true
num-points = 11
file-name-appendix = "_epoch15"

[cnn-curve-evaluate-point]
dir = "results/MNIST_CNN/evaluation_curve"
dataset = "mnist"
data-path = "datasets/"
model = "CNN"
curve = "Bezier"
num-bends = 1
wd = 0.0005
ckpt = "results/MNIST_CNN/checkpoints_curve/model-weights-epoch15"
init-linear = false
fix-start = true
fix-end = true
point-on-curve = 0.5
save-evaluation = false

[cnnbn-base-model-1]
dir = "results/MNIST_CNNBN/checkpoints_base_model_1"
dataset = "mnist"
data-path = "datasets/"
model = "CNNBN"
epochs = 10
lr = 0.05
wd = 0.0005
seed = 1

[cnnbn-base-model-2]
dir = "results/MNIST_CNNBN/checkpoints_base_model_2"
dataset = "mnist"
data-path = "datasets/"
model = "CNNBN"
epochs = 10
lr = 0.05
wd = 0.0005
seed = 42

[cnnbn-curve-pretrained]
dir = "results/MNIST_CNNBN/checkpoints_curve"
dataset = "mnist"
data-path = "datasets/"
model = "CNNBN"
curve = "Bezier"
num-bends = 1
epochs = 10
lr = 0.05
wd = 0.0005
init-start = "results/MNIST_CNNBN/checkpoints_base_model_1/model-weights-epoch10"
fix-start = true
init-end = "results/MNIST_CNNBN/checkpoints_base_model_2/model-weights-epoch10"
fix-end = true

[cnnbn-curve-resume]
dir = "results/MNIST_CNNBN/checkpoints_curve"
dataset="mnist"
data-path="datasets/"
ckpt="results/MNIST_CNNBN/checkpoints_curve/model-weights-epoch10"
resume-epoch=11
model="CNNBN"
curve="Bezier"
num-bends=1
epochs=15
lr=0.001
wd=0.0005
fix-start = true
fix-end = true

[cnnbn-curve-evaluate-init]
dir = "results/MNIST_CNNBN/evaluation_curve"
dataset = "mnist"
data-path = "datasets/"
model = "CNNBN"
curve = "Bezier"
num-bends = 1
wd = 0.0005
ckpt = "results/MNIST_CNNBN/checkpoints_curve/model-weights-epoch0"
init-linear = false
fix-start = true
fix-end = true
num-points = 11
file-name-appendix = "_epoch0"

[cnnbn-curve-evaluate-trained]
dir = "results/MNIST_CNNBN/evaluation_curve"
dataset = "mnist"
data-path = "datasets/"
model = "CNNBN"
curve = "Bezier"
num-bends = 1
wd = 0.0005
ckpt = "results/MNIST_CNNBN/checkpoints_curve/model-weights-epoch15"
init-linear = false
fix-start = true
fix-end = true
num-points = 11
file-name-appendix = "_epoch15"

[cnnbn-curve-evaluate-point]
dir = "results/MNIST_CNNBN/evaluation_curve"
dataset = "mnist"
data-path = "datasets/"
model = "CNNBN"
curve = "Bezier"
num-bends = 1
wd = 0.0005
ckpt = "results/MNIST_CNNBN/checkpoints_curve/model-weights-epoch15"
init-linear = false
fix-start = true
fix-end = true
point-on-curve = 0.5
save-evaluation = false

[mlp-base-model-1]
dir = "results/Regression_MLP/checkpoints_base_model_1"
dataset = "regression"
data-path = "datasets/"
model = "MLP"
epochs = 150
lr = 0.001
wd = 0.0005
seed = 1

[mlp-base-model-2]
dir = "results/Regression_MLP/checkpoints_base_model_2"
dataset = "regression"
data-path = "datasets/"
model = "MLP"
epochs = 150
lr = 0.001
wd = 0.0005
seed = 42

[mlp-curve-pretrained]
dir = "results/Regression_MLP/checkpoints_curve"
dataset = "regression"
data-path = "datasets/"
model = "MLP"
curve = "Bezier"
num-bends = 5
epochs = 100
lr = 0.01
wd = 0.0005
init-start = "results/Regression_MLP/checkpoints_base_model_1/model-weights-epoch150"
fix-start = true
init-end = "results/Regression_MLP/checkpoints_base_model_2/model-weights-epoch150"
fix-end = true

[mlp-curve-resume]
dir = "results/Regression_MLP/checkpoints_curve"
dataset="regression"
data-path="datasets/"
ckpt="results/Regression_MLP/checkpoints_curve/model-weights-epoch100"
resume-epoch=101
model="MLP"
curve="Bezier"
num-bends=5
epochs=150
lr=0.0001
wd=0.0005
fix-start = true
fix-end = true

[mlp-curve-evaluate-init]
dir = "results/Regression_MLP/evaluation_curve"
dataset = "regression"
data-path = "datasets/"
model = "MLP"
curve = "Bezier"
num-bends = 5
wd = 0.0005
ckpt = "results/Regression_MLP/checkpoints_curve/model-weights-epoch0"
init-linear = false
fix-start = true
fix-end = true
num-points = 11
file-name-appendix = "_epoch0"

[mlp-curve-evaluate-trained]
dir = "results/Regression_MLP/evaluation_curve"
dataset = "regression"
data-path = "datasets/"
model = "MLP"
curve = "Bezier"
num-bends = 5
wd = 0.0005
ckpt = "results/Regression_MLP/checkpoints_curve/model-weights-epoch150"
init-linear = false
fix-start = true
fix-end = true
num-points = 11
file-name-appendix = "_epoch150"

[mlp-curve-evaluate-point]
dir = "results/Regression_MLP/evaluation_curve"
dataset = "regression"
data-path = "datasets/"
model = "MLP"
curve = "Bezier"
num-bends = 5
wd = 0.0005
ckpt = "results/Regression_MLP/checkpoints_curve/model-weights-epoch150"
init-linear = false
fix-start = true
fix-end = true
point-on-curve = 0.5
save-evaluation = false